[build]
  command = "npm install && npx prisma generate"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", ".prisma/client"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
